export const userActionsTypes = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
  PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
  PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

  PROFILES_LIST_REQUEST: 'PROFILES_LIST_REQUEST',
  PROFILES_LIST_SUCCESS: 'PROFILES_LIST_SUCCESS',
  PROFILES_LIST_FAILURE: 'PROFILES_LIST_FAILURE',
  PROFILES_LIST_MODIFY: 'PROFILES_LIST_MODIFY',

  LOGOUT: 'USERS_LOGOUT',
};

export const alertActionsTypes = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  HIDE: 'ALERT_HIDE'
};

export const testsActionsTypes = {
  TESTS_LIST_SUCCESS: 'TESTS_LIST_SUCCESS',
  TESTS_LIST_FAILED: 'TESTS_LIST_FAILED',
  TESTS_LIST_REQUEST: 'TESTS_LIST_REQUEST',
  TESTS_LIST_MODIFY: 'TESTS_LIST_MODIFY',

  TESTS_CREATE_SUCCESS: 'TESTS_CREATE_SUCCESS',
  TESTS_CREATE_FAILED: 'TESTS_CREATE_FAILED',
  TESTS_CREATE_REQUEST: 'TESTS_CREATE_REQUEST',
};

export const singleTestActionsTypes = {
  TESTS_LIST_SUCCESS: 'SINGLE_TEST_SUCCESS',
  TESTS_LIST_FAILED: 'SINGLE_TEST_FAILED',
  TESTS_LIST_REQUEST: 'SINGLE_TEST_REQUEST',
};
